services:
  
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "127.0.0.1:9000:8075"
    volumes:
      - ./:/var/www
    networks:
      - laravel-net
    command: /var/www/docker/php/start-dev.sh
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    ports:
    - "33066:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel-net
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  vite:
    build:
      context: .
      dockerfile: docker/vite/Dockerfile
    container_name: laravel_vite
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    networks:
      - laravel-net
    depends_on:
      - app 

networks:
  laravel-net:
    driver: bridge

volumes:
  db-data: